import React from 'react';

export default function BitcoinMining() {
  return (
    <div className='Bitcoin'>
      <h1>Bitcoin</h1>
      <p>
      Bitcoin (BTC) is a cryptocurrency, a virtual currency designed to act as money and a form of payment outside the control of any one person, group, or entity, and thus removing the need for third-party involvement in financial transactions. It is rewarded to blockchain miners for the work done to verify transactions and can be purchased on several exchanges. Have you ever wonder how bitcoin came into existence?
      </p>
      <p>
      Bitcoin was introduced to the public in 2009 by an anonymous developer or group of developers using the name Satoshi Nakamoto. It has since become the most well-known cryptocurrency in the world. Its popularity has inspired the development of many other cryptocurrencies. These competitors either attempt to replace it as a payment system or are used as utility or security tokens in other blockchains and emerging financial technologies.In August 2008, the domain name Bitcoin organization was registered.
      </p>
      <p>
      Today, at least, this domain is WhoisGuard Protected, meaning the identity of the person who registered it is not public information.
      </p>
      <p>
      In October 2008, a person or group using the false name Satoshi Nakamoto announced the Cryptography Mailing List : "I've been working on a new electronic cash system that's fully peer-to-peer, with no trusted third party." This now-famous white paper published on Bitcoin organizations entitled "Bitcoin: A Peer-to-Peer Electronic Cash System," would become the Magna Carta for how Bitcoin operates today.
      </p>
      <p>
      On Jan. 3, 2009, the first Bitcoin block was mined—Block 0. This is also known as the "genesis block" and contains the text: "The Times 03/Jan/2009 Chancellor on brink of second bailout for banks," perhaps proof that the block was mined on or after that date, and maybe also as relevant political commentary.
      </p>
      <p>
      Bitcoin rewards are halved every 210,000 blocks. For example, the block reward was 50 new bitcoins in 2009. On May 11, 2020, the third halving occurred, bringing the reward for each block discovery down to 6.25 bitcoins.
      </p>
      <p>
      One bitcoin is divisible to eight decimal places (100 millionths of one bitcoin), and this smallest unit is referred to as a satoshi. If necessary, and if the participating miners accept the change, Bitcoin could eventually be made divisible to even more decimal places.
      </p>
      <p>
      Bitcoin, as a form of digital currency, isn't too complicated to understand. For example, if you own a bitcoin, you can use your cryptocurrency wallet to send smaller portions of that bitcoin as payment for goods or services. However, it becomes very complex when you try to understand how it works.
      </p>
      <h2>Did you know You can earn by mining bitcoins?</h2>
      <p>
      Bitcoin mining is the process of creating new bitcoin by solving puzzles. It consists of computing systems equipped with specialized chips competing to solve mathematical puzzles. The first bitcoin miner (as these systems are called) to solve the puzzle is rewarded with bitcoin. The mining process also confirms transactions on the cryptocurrency's network and makes them trustworthy.
      </p>
      <p>
      Just as gold is mined from the earth using large implements and machines, bitcoin mining also uses big systems akin to data centers. These systems solve mathematical puzzles generated by Bitcoin's algorithm to produce new coins.
      </p>
      <p>
      By solving computational math problems, bitcoin miners also make the cryptocurrency's network trustworthy by verifying its transaction information. They verify 1 megabyte (MB) worth of transactions—the size of a single block.
      </p>
      <p>
      Transactions are placed into a queue to be validated by miners within the network. Miners in the Bitcoin blockchain network all attempt to verify the same transaction simultaneously. The mining software and hardware work to solve the nonce, a four-byte number included in the block header that miners are attempting to solve. The block header is hashed, or randomly regenerated by a miner repeatedly until it meets a target number specified by the blockchain. The block header is "solved," and a new block is created for more transactions to be encrypted and verified.
      </p>
      <p>
      Our Bitcoin mining machines(S9i Antminer(Upgraded) 15.2TH/s+ )let you mine the price of Bitcoin (based on the trusted TeraBit algorithm ) without having to own a mining machines.
      </p>
      <h2>Machine Packages</h2>
      <br></br>
      <p>Select any package that is suitable to you.</p>
      <br></br>
      <p>Widget Pack 1 (2 Machines)</p>
      <p>Min Deposit : 0.5btc</p>
      <p>Rewards :5%-10%</p>
      <br></br>
      <p>Widget pack 2 (4 machines)</p>
      <p>Min Deposit:3btc</p>
      <p>Rewards: 10%-20%</p>
      <br></br>
      <p>Widget pack 3 ( 8 machines)</p>
      <p>Min Deposit: 5btc</p>
      <p>Rewards: 20%-30%</p>
      <br></br>
      <p>Widget pack 4( 16 machines)</p>
      <p>Min Deposit: 10btc</p>
      <p>Rewards: 30%-50%</p>
      <br></br>
      <p>Widget pack 5 ( 32 machines)</p>
      <p>Min Deposit: 15btc</p>
      <p>Rewards:50%-100%</p>
    </div>
  );
}